# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
client_id = "437bb26d52c979f5af4a3c703c0f398e"
name = "Hera Fulfiller"
application_url = "https://hera-fulfiller.onrender.com/"
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
scopes = "read_analytics,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_customers,write_customers,read_fulfillments,write_fulfillments,write_inventory,read_inventory,write_inventory_shipments,read_inventory_shipments,write_inventory_shipments_received_items,read_inventory_shipments_received_items,write_inventory_transfers,read_inventory_transfers,read_locations,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_order_edits,read_orders,write_orders,read_products,write_products,read_shipping,write_shipping,read_third_party_fulfillment_orders,write_third_party_fulfillment_orders"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = ["https://hera-fulfiller.onrender.com/auth/callback"]